import React from 'react'
import { GetServerSidePropsContext, InferGetServerSidePropsType } from 'next'
import Head from 'next/head'
import { appRouter } from '@/shared/server/routers/_app'
import { trpc } from '@/shared/utils/trpc'
import { createServerSideHelpers } from '@trpc/react-query/server'
import superjson from 'superjson'

import { Scroll } from '@/components/scroll'
import { ScrollMost } from '@/components/scroll-pop'

export async function getServerSideProps() {
  const helpers = createServerSideHelpers({
    router: appRouter,
    ctx: {},
    transformer: superjson,
  })
  await helpers.manga.getMangaPopular.prefetch()
  // const data = await mangaControllerGetMankaPopular();
  return {
    props: {
      trpcState: helpers.dehydrate(),
    },
  }
}
function MainManga(props: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const { data: manga } = trpc.manga.getMangaPopular.useQuery(undefined, {
    refetchOnMount: false,
    refetchOnWindowFocus: false,
  })
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" h-full w-full border-[1px] border-pink-600">
        <section className="items-center justify-center ">
          <Scroll></Scroll>
        </section>
        <section className="">
          <h1 className="text-4xl md:text-2xl">The most popular now</h1>
          <ScrollMost popular={manga}></ScrollMost>
        </section>
      </main>
    </>
  )
}

export default MainManga
